# Introduccion a R

## ¿Que es R? 

R es un lenguaje de programación especializado en el procesamiento, visualización y análisis de datos. Aunque hay otros lenguajes más genéricos y flexibles, R brilla por su capacidad para el análisis de datos. Hay quien se refiere a R como la lingua franca de la estadística, pero es mucho más que eso como tendremos ocasión de ver más adelante. 

Su primera versión, que fue creada por dos profesores neozelandeses, Ross Ihaka y Robert Gentleman, data de 1993 y este libro está escrito con la versión 4.0.0 que fue distribuida en la primavera del 2020. Su popularidad, tanto en la comunidad científica como fuera de ella, no ha parado de crecer. El ranking Tiobe de lenguajes de programación situaba a R como el noveno lenguaje de programación más popular en junio del 2020. 

R es también un entorno de programación. Es la aplicación que traduce el lenguaje R, un lenguaje que los humanos podemos entender, a código binario, un lenguaje que una maquina puede entender, para que la unidad de procesado central de tu ordenador pueda hacer lo que tú le estas pidiendo. Como entorno es bastante espartano en apariencia. Al abrir R lo único que vemos es una consola con un cursor en la que se puede programar de forma interactiva.

Normalmente cuando los profesionales interactuamos con R lo hacemos no directamente, sino a través de algún interfaz diseñado para mejorar la labor del analista/programador. En este manual usamos RStudio que es probablemente el mejor y mas popular de estas aplicaciones. RStudio ofrece una versión gratuita que en funcionalidad no se diferencia de forma relevante de su versión de pago.

R y RStudio pueden ser instalados en dispositivos que usan distintos sistemas operativos: Windows, Linux o Mac OS. R puede ser obtenido en la página de internet del *Comprehensive R Archive Network (CRAN)*: https://cran.r-project.org/. Mientras que la aplicación de escritorio de RStudio puede ser obtenido en la página de internet de RStudio (https://rstudio.com/products/rstudio/download/#download). YOUTUBE está cargado de tutoriales para la obtención e instalación tanto de R como de RStudio. Es fácil y no le dedicaremos más atención aquí.

## ¿Por qué R para las ciencias sociales?

En España tradicionalmente se ha empleado un producto comercial de IBM, SPSS, como la principal herramienta para enseñar análisis de datos en las ciencias sociales. Comparar SPSS a R es como comparar un autobús donde tu eres el pasajero y solo puedes ir a las paradas de una ruta (pagando un auténtico dineral en licencia de uso) con un batmovil gratuito donde tú, Batman, conduces donde quieres, vuelas, vas bajo el agua, y tienes todo tipo de gadgets fabulosos. Hay otros productos comerciales como STATA o SAS que también son populares aplicaciones comerciales, pero R presenta ventajas importantes frente a estos productos, más allá de su coste. 

La instalación básica de R tiene una funcionalidad básica, pero como lenguaje abierto cualquier usuario puede extender esta funcionalidad. Decíamos anteriormente que R es un entorno de programación. A diferencia de otras aplicaciones que tienen una funcionalidad determinada por sus programadores, si hay algo que R no puede hacer nada impide a un usuario programar R para que lo haga. Hoy en día existen 15781 “paquetes” oficiales (si eres un gamer puedes pensar que un paquete es como un mod) que extienden la funcionalidad de R. Cualquier persona con suficientes conocimientos puede escribir un paquete de R a estos efectos (¿quizás tu un día?). Cada vez que un profesor de estadística o métodos diseña una nueva modalidad de análisis o visualización de datos es muy común que estas mismas personas creen un paquete de R implementando este nuevo método. Eso hace que el ciclo de adaptación e innovación metodológica en R sea mucho más rápido que en los programas comerciales. De hecho, existen actualizaciones de R cada 6 meses aproximadamente y el ritmo de crecimiento de paquetes creados por usuarios de R.

R esta mucho mas adaptado que SPSS o STATA para procesar bases de datos de gran volumen y maneja estructuras de datos muy flexibles, lo que lo hace particularmente útil para procesar, por ejemplo, datos relacionales (para análisis de redes sociales), espaciales (para visualización cartográfica), textuales (que pueden ser sometidas a análisis cualitativos empleando R), escarbado de páginas web (web scraping). o incluso imágenes. En otras palabras, esta mucho más preparado para el tipo de datos que han adquirido mas relevancia en las ciencias sociales en las ultimas décadas.

Programas como SPSS han facilitado, casi incentivado por diseño, el análisis por medio del uso de menus; usando el cursor de tu ratón, cliqueando, y seleccionando opciones. Existen aplicaciones que permiten esta forma de interactuar con R (jamovi, inzight, y RCommander son probablemente las más populares). No obstante, este tipo de proceder, sobre todo cuando hablamos de una aplicación que no esta al alcance de todo el mundo, hace más difícil la reproducibilidad de los análisis. El uso de programación para generar análisis incentiva la creación de un registro escrito que se puede compartir con otras personas, incluso con tu futuro yo, para intentar reproducir los análisis originales. En el contexto actual de la ciencia las practicas reproducibles son esenciales para inspirar confianza en los resultados que obtenemos.

R y RStudio son herramientas muy poderosas para generar productos analíticos y para presentar nuestros resultados. Este libro está escrito usando solo R. Mi blog personal (www.juanjomedina.com) y las páginas que sirven de apoyo a este manual están escritos usando R. también podemos usar estas herramientas para generar presentaciones de diapositivas o plataformas interactivas de análisis en el internet.

Ningún listado de las ventajas de R seria completa sin incluir a su comunidad de usuarios. Miles y miles de científicos, analistas y programadores usan y contribuyen al desarrollo y control de calidad de R. A diferencia del software comercial, el código de R está auditado por la comunidad de programadores y usuarios de R. Al margen de cumplir una función de desarrollo y control de calidad, los usuarios de R son tutores apasionados dispuestos a solventar dudas y explicar cómo usar R. Internet está plagado de tutoriales, demonstraciones, y cursos gratuitos diseñados por usuarios de R. En muchas ciudades y en muchos países existen organizaciones de usuarios de R que realizan reuniones locales generalmente abiertas a cualquiera con un interés en el uso de R. Probablemente cualquier problema o pregunta que tengas sobre R en algún momento ya ha sido discutido o respondido previamente en algún lugar del ciberespacio, lo cual facilita el confrontar nuestras dudas sobre el uso de R.

## Explorando (superficial y rapidamente) el interfaz de RStudio

Como hemos indicado es posible usar R sin emplear RStudio, pero RStudio ofrecen numerosas ventajas. RStudio es técnicamente un entorno integrado de desarrollo que facilita un flujo de trabajo reproducible y desarrollar nuestros análisis de forma más eficiente. Cuando iniciamos RStudio estamos al mismo tiempo iniciando una sesión de R. Al iniciar RStudio por primera vez (como se ve en la Figura 1) veremos que la pantalla aparece dividida en tres paneles, así como una serie de menús en la barra superior (Files, Edit, Code, View, etc.). A fecha de hoy no existe una versión de RStudio para usuarios que solo hablan español, pero esto no debería ser un inconveniente severo.

El panel principal a la izquierda es **la consola** de R. Si usáramos R sin RStudio esto es básicamente todo lo que veríamos. En la parte superior se vera la versión de R que está instalada en vuestra máquina. También observamos un cursor en el que podemos escribir comandos de R y presionando "Enter" obtener algún tipo de resultado. Es decir, podemos trabajar con R de esta forma interactiva, pero lo más común es hacerlo de forma que generemos un registro escrito algo más permanente por medio de la creación de un "**script**".

Para iniciar un *script* podemos acudir al menú "File", seleccionar "New File", y entonces "R Script". De forma alternativa podemos usar el atajo "Ctrl+Shift+n" para generar un nuevo *script* (RStudio ofrece numerosos de estos atajos que se pueden acceder tecleando "Alt+Shift+k"). ¿Qué es un script? Es simplemente un editor de texto que se puede (y debe) grabar como un fichero para así guardar un registro de nuestro código analítico. El pequeño diskette representado en la parte superior del editor puede usarse para guardar el archivo, que se almacenara con la terminación .r, pero que en esencia es implemente un fichero textual que se puede también abrir con una aplicación como Notepad. también se puede grabar el editor *que tengamos activo* usando "Ctrl+s".

Una vez tenemos el editor de texto abierto vemos la pantalla dividida en cuatro porciones que pueden reajustarse en tamaño usando el cursor. El editor ocupa la parte superior izquierda, mientras que la consola pasa a la parte inferior izquierda. En la parte superior derecha tenemos un conjunto de ventanas. La más importante para el principiante es el **"Environment"** o entorno de trabajo. De momento podemos ignorar las otras. El entorno de trabajo es algo así como una especie de almacén en el que viven (durante tu sesión) los datos que empleas en tus análisis, así como los distintos objetos y resultados generados por tu procesamiento de datos y análisis. R trabaja usando el RAM de tu maquina y el entorno de trabajo básicamente ocupa una porción de tu RAM mientras trabajas con R.

La parte inferior derecha tiene varias ventanas que son útiles. Las más importantes son: Files, Plots, Packages y Help. **Files** es similar a Windows Explorer. Básicamente te ofrece una visualización de la estructura de tu disco duro, distintas carpetas y archivos. Generalmente lo ideal es que apunte a la carpeta de trabajo desde la que estas realizando tus análisis. **Plots** es donde se visualizarán las representaciones gráficas de datos que generemos con nuestros análisis. **Packages** es donde ves los distintos paquetes que están instalados en tu disco duro, aso como aquellos que son activos en tu sesión de R. Finalmente, en **Help** tenéis acceso a la documentación técnica de R. La documentación técnica de R está escrita para programadores. Requiere práctica el entender esta documentación. Más útiles son las viñetas (vignettes) que autores de paquetes incluyen a menudo (no siempre) dentro de esta documentación técnica y que suele estar orientada a explicar la funcionalidad y uso de los paquetes.

## Tuneando RStudio

RStudio tiene una serie de opciones configuradas al instalarse que pueden cambiarse y yo recomiendo cambiar. En el menu *Tools* se puede seleccionar *Global Options*. En la pantalla que se abre podemos observar varios submenus. En el menu general yo recomiendo asegurarnos que **nunca** grabamos nuestro entorno de trabajo a un archivo de .RData y que no restauramos el entorno de trabajo de la ultima sesion. Para ello asegurense de que la casilla al lado de "Restore .RData 

Esto es para garantizar algo de higiene a la hora de trabajar con RStudio. Sobre todo para los principiantes el empezar la sesion con un entorno de trabajo populado por los restos del trabajo de la sesion anterior suele generar confusiones en el aprendizaje de R. Esto tambien sirve para reiterar que lo que es real no es lo que existe en entorno de trabajo, lo que es real es el codigo escrito que genera lo que veremos aparecer en ese entorno como una consecuencia de ejecutar este codigo escrito. Mientras tengamos este codigo escrito archivado no necesitamos tener una copia del entorno de trabajo, porque siempre podemos reproducirlo. Ahora mismo estas consideraciones pueden ser un poco extranas ya que no hemos empezado a usar R y puede ser dificil entender asi en abstracto, pero confien en mi. Cambien estas opciones. Asegurense de seleccionar "Apply" antes de cerrar el menu de Global Options.

Otra sugerencia, menos importante desde un punto de vista operativo, es cambiar el aspecto de RStudio. En el menu 

